services:
    cms:
        build: docker/services/backend
        container_name: cms-cms
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/volumes/config/config.php:/app/config/config.php
            - caddy_data:/data
            - caddy_config:/config
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - "61000:80"
            - "61001:443"
            - "61001:443/udp"
        environment:
            #- FRANKENPHP_CONFIG="worker ./public/index.php"
            - SERVER_NAME=":80"
            - DATABASE_URL="mysql://cms:cms@cms-database:3306/cms"

    database:
        image: mariadb:10
        container_name: cms-database
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_PASSWORD=cms
        ports:
            - "61002:3306"

volumes:
    database:
    caddy_data:
    caddy_config:
