<?php /* Smarty version 2.6.30, created on 2019-05-16 20:38:36
         compiled from Proxia:default.array_pager */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('insert', 'initialize_array_pager_vars', 'Proxia:default.array_pager', 3, false),array('insert', 'formGet', 'Proxia:default.array_pager', 13, false),array('insert', 'tr', 'Proxia:default.array_pager', 26, false),array('insert', 'urlGet', 'Proxia:default.array_pager', 31, false),array('function', 'assignel', 'Proxia:default.array_pager', 9, false),)), $this); ?>
<?php echo ''; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'initialize_array_pager_vars', 'list' => $this->_tpl_vars['list'])), $this); ?><?php echo ''; ?><?php if (( $this->_tpl_vars['qs'] == 0 ) || ( $this->_tpl_vars['perpage'] < $this->_tpl_vars['p_totalRecordCount'] )): ?><?php echo '<table align="right" width="550" border="0"><tr><form method="get" name="pager" id="pager">'; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 0,'value' => 'form_text_name'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 1,'value' => 'form_name'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 2,'value' => 'setPerPage'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 3,'value' => 'start'), $this);?><?php echo ''; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'formGet', 'hidden' => $this->_tpl_vars['novisible'], 'assign' => 'link')), $this); ?><?php echo ''; ?><?php echo $this->_tpl_vars['link']; ?><?php echo '<td width="150">&nbsp;&nbsp;<select name="setPerPage" onchange="pager.submit()"><option value="10" '; ?><?php if ($this->_tpl_vars['perpage'] == 10): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>10</option><option value="20" '; ?><?php if ($this->_tpl_vars['perpage'] == 20): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>20</option><option value="50" '; ?><?php if ($this->_tpl_vars['perpage'] == 50): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>50</option><option value="100" '; ?><?php if ($this->_tpl_vars['perpage'] == 100): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>100</option><option value="200" '; ?><?php if ($this->_tpl_vars['perpage'] == 200): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>200</option><option value="999999" '; ?><?php if ($this->_tpl_vars['perpage'] == null || $this->_tpl_vars['perpage'] == 999999): ?><?php echo 'selected="selected"'; ?><?php endif; ?><?php echo '>všetky záznamy</option></select></td></form><td width="250">'; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'Počet záznamov')), $this); ?><?php echo ' '; ?><?php echo $this->_tpl_vars['p_size']; ?><?php echo ' '; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'z celkovo')), $this); ?><?php echo ' '; ?><?php echo $this->_tpl_vars['p_totalRecordCount']; ?><?php echo '</td>'; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 0,'value' => 'form_text_name'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 1,'value' => 'form_name'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 2,'value' => 'setPerPage'), $this);?><?php echo ''; ?><?php echo smarty_function_assignel(array('var' => 'novisible','key' => 3,'value' => 'start'), $this);?><?php echo ''; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'urlGet', 'hidden' => $this->_tpl_vars['novisible'], 'assign' => 'link')), $this); ?><?php echo ''; ?><?php if (( $this->_tpl_vars['p_currentPage'] > 1 )): ?><?php echo '<td align="center" width="37"><a href="./?start='; ?><?php echo $this->_tpl_vars['p_firstStart']; ?><?php echo ''; ?><?php echo $this->_tpl_vars['link']; ?><?php echo '" title="'; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'Úvodná stránka')), $this); ?><?php echo '"><img src="images/p_start.png" /></a></td><td align="center" width="37"><a href="./?start='; ?><?php echo $this->_tpl_vars['p_previousStart']; ?><?php echo ''; ?><?php echo $this->_tpl_vars['link']; ?><?php echo '" title="'; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'Predchádzajúca stránka')), $this); ?><?php echo '"><img src="images/p_back.png" /></a></td>'; ?><?php else: ?><?php echo '<td align="center" width="37"></td><td align="center" width="37"></td>'; ?><?php endif; ?><?php echo '<td width="40">'; ?><?php echo $this->_tpl_vars['p_currentPage']; ?><?php echo '/'; ?><?php echo $this->_tpl_vars['p_pageCount']; ?><?php echo '</td>'; ?><?php if (( $this->_tpl_vars['p_nextStart'] < $this->_tpl_vars['p_totalRecordCount'] ) && ( $this->_tpl_vars['p_nextStart'] != 0 )): ?><?php echo '<td align="center" width="38"><a href="./?start='; ?><?php echo $this->_tpl_vars['p_nextStart']; ?><?php echo ''; ?><?php echo $this->_tpl_vars['link']; ?><?php echo '" title="'; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'Ďalšia stránka')), $this); ?><?php echo '"><img src="images/p_next.png" /></a></td><td align="center" width="38"><a href="./?start='; ?><?php echo $this->_tpl_vars['p_lastStart']; ?><?php echo ''; ?><?php echo $this->_tpl_vars['link']; ?><?php echo '" title="'; ?><?php require_once(SMARTY_CORE_DIR . 'core.run_insert_handler.php');
echo smarty_core_run_insert_handler(array('args' => array('name' => 'tr', 'value' => 'Posledná stránka')), $this); ?><?php echo '"><img src="images/p_end.png" /></a></td>'; ?><?php else: ?><?php echo '<td align="center" width="38"></td><td align="center" width="38"></td>'; ?><?php endif; ?><?php echo '</tr></table>'; ?><?php endif; ?><?php echo ''; ?>
